dubbo:
  application:
    name: learn-dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181 # zookeeper 注册中心地址

server:
  port: 80

zookeeper:
  connectString: 127.0.0.1:2181
  maxRetries: 3
  baseSleepTimeMs: 1000