dubbo:
  application:
    name: learn-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181  # zookeeper 注册中心地址
  protocol:
    name: dubbo
    port: 20880  # dubbo 协议端口，默认为20880
server:
  port: 81
