// automatically generated by the FlatBuffers compiler, do not modify

package com.a3fun.learn.sb.protocol;

public final class MessageType {
  private MessageType() { }
  public static final int CSGetRoleInfo = 0;
  public static final int SCRoleInfo = 10;
}

