// automatically generated by the FlatBuffers compiler, do not modify

package com.a3fun.learn.sb.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SCRoleInfo extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static SCRoleInfo getRootAsSCRoleInfo(ByteBuffer _bb) { return getRootAsSCRoleInfo(_bb, new SCRoleInfo()); }
  public static SCRoleInfo getRootAsSCRoleInfo(ByteBuffer _bb, SCRoleInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SCRoleInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String roleName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roleNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer roleNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long exp() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int level() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String description() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String avatar() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer avatarInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public long gold() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long freeDiamond() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long rechargeDiamond() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String pveId() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pveIdAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer pveIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }
  public String character() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer characterAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public ByteBuffer characterInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 1); }
  public String bgPic() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bgPicAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer bgPicInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }

  public static int createSCRoleInfo(FlatBufferBuilder builder,
      int role_nameOffset,
      long exp,
      int level,
      int descriptionOffset,
      int avatarOffset,
      long gold,
      long free_diamond,
      long recharge_diamond,
      int pve_idOffset,
      int characterOffset,
      int bg_picOffset) {
    builder.startTable(11);
    SCRoleInfo.addRechargeDiamond(builder, recharge_diamond);
    SCRoleInfo.addFreeDiamond(builder, free_diamond);
    SCRoleInfo.addGold(builder, gold);
    SCRoleInfo.addExp(builder, exp);
    SCRoleInfo.addBgPic(builder, bg_picOffset);
    SCRoleInfo.addCharacter(builder, characterOffset);
    SCRoleInfo.addPveId(builder, pve_idOffset);
    SCRoleInfo.addAvatar(builder, avatarOffset);
    SCRoleInfo.addDescription(builder, descriptionOffset);
    SCRoleInfo.addLevel(builder, level);
    SCRoleInfo.addRoleName(builder, role_nameOffset);
    return SCRoleInfo.endSCRoleInfo(builder);
  }

  public static void startSCRoleInfo(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addRoleName(FlatBufferBuilder builder, int roleNameOffset) { builder.addOffset(0, roleNameOffset, 0); }
  public static void addExp(FlatBufferBuilder builder, long exp) { builder.addLong(1, exp, 0L); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(2, level, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(3, descriptionOffset, 0); }
  public static void addAvatar(FlatBufferBuilder builder, int avatarOffset) { builder.addOffset(4, avatarOffset, 0); }
  public static void addGold(FlatBufferBuilder builder, long gold) { builder.addLong(5, gold, 0L); }
  public static void addFreeDiamond(FlatBufferBuilder builder, long freeDiamond) { builder.addLong(6, freeDiamond, 0L); }
  public static void addRechargeDiamond(FlatBufferBuilder builder, long rechargeDiamond) { builder.addLong(7, rechargeDiamond, 0L); }
  public static void addPveId(FlatBufferBuilder builder, int pveIdOffset) { builder.addOffset(8, pveIdOffset, 0); }
  public static void addCharacter(FlatBufferBuilder builder, int characterOffset) { builder.addOffset(9, characterOffset, 0); }
  public static void addBgPic(FlatBufferBuilder builder, int bgPicOffset) { builder.addOffset(10, bgPicOffset, 0); }
  public static int endSCRoleInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SCRoleInfo get(int j) { return get(new SCRoleInfo(), j); }
    public SCRoleInfo get(SCRoleInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

